apiVersion: v1
kind: Service
metadata:
    name: backend-db
spec:
    clusterIP: None
    selector:
        app: blokmap
        environment: staging
        tier: backend
        component: database
    ports:
      - protocol: TCP
        port: 5432
        targetPort: 5432
