apiVersion: v1
kind: PersistentVolume
metadata:
    name: auth-db
    labels:
        app: blokmap
        environment: staging
        tier: auth
        component: volume
        related-to: database
spec:
    storageClassName: manual
    capacity:
        storage: 50Gi
    accessModes:
        - ReadWriteOncePod
    hostPath:
        path: "/home/tibo/blokmap-auth-data"
