apiVersion: v1
kind: Service
metadata:
    name: backend-cache
spec:
    clusterIP: None
    selector:
        app: blokmap
        environment: staging
        tier: backend
        component: cache
    ports:
      - protocol: TCP
        port: 6379
        targetPort: 6379
